### ISSUE TITLE
Remove `using std::experimental::{optional, nullopt, string_view}` from flags namespace.

### ISSUE THREAD

**Issue by sailormoon** [sailormoon/flags#1]
Out of laziness, and because std::experimental is such a long namespace, `using std::experimental::{optional, nullopt, string_view}` was used in the flags namespace. It should be removed when when both optional and string_view are moved into `std` proper.

**Comment by dancsi** [comment]
You can also check which set of headers exists by using the `__has_include` preprocessor macro.
