### ISSUE TITLE
Boolean options return false if no value was specified in the command line

### ISSUE THREAD

**Issue by yahiaetman** [sailormoon/flags#8]
**Steps to reproduce:**
1. Copy the example to a file named `src.cpp`
```
#include "flags.h"
#include <iostream>

int main(int argc, char** argv) {
  const flags::args args(argc, argv);

  const auto count = args.get<int>("count");
  if (!count) {
    std::cerr << "No count supplied. :(\n";
    return 1;
  }
  std::cout << "That's " << *count << " incredible, colossal credits!\n";

  if (args.get<bool>("laugh", false)) {
    std::cout << "Ha ha ha ha!\n";
  }
  return 0;
}
```
2. Add `flags.h` to the same folder.
3. Compile using `clang src.cpp -std=c++17 -o program.exe`
4. Run using `.\program.exe --count 5 --laugh`

**Expected result:**
```
That's 5 incredible, colossal credits!
Ha ha ha ha!
```

**Actual result:**
```
That's 5 incredible, colossal credits!
```

**Environment:**

- **OS:** Windows 10
- **Compiler:** Clang 9.0.0

**Reason behind the issue:**
```
template <>
std::optional<bool> get(const argument_map& options,
                        const std::string_view& option) {
  if (const auto value = get_value(options, option)) {
    return std::none_of(falsities.begin(), falsities.end(),
                        [&value](auto falsity) { return *value == falsity; });
  }
  return std::nullopt;
}
```
In the aforementioned code, the function cannot differentiate between the two scenarios:

1. `.\program.exe --count 5 --laugh`
2. `.\program.exe --count 5`

Since in both cases, `args.get<bool>("laugh")` will return `std::nullopt`.

**Suggested fix:**
Check if the option exists in the `options` map.
```
template <>
std::optional<bool> get(const argument_map& options,
                        const std::string_view& option) {
  if (const auto value = get_value(options, option)) {
    return std::none_of(falsities.begin(), falsities.end(),
                        [&value](auto falsity) { return *value == falsity; });
  }
  if (options.find(option) != options.end())
      return true;
  return std::nullopt;
}
```

**Comment by MrMusic25** [comment]
Glad I wasn't the only one running into this issue, thought I was going crazy when the included "verbose" example in the README wasn't working properly. Tried the included changes, they fix the problem for me!
